### ISSUE TITLE
[admin-api] Does not handle bad admin api key

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost-SDK#149]
See https://forum.ghost.org/t/cannot-read-property-split-of-undefined-error-with-ghost-admin-api-on-aws-lambda/8754

If an invalid admin api key is provided then it can result in an unhandled error `cannot read property 'split' of undefined`

**Comment by mikemimik** [comment]
Hey @kevinansfield, sorry to hear you're having issues. I added a catch block for this in the module, and updated the tests around config validation. 

Thanks so much for committing to open source!
