### ISSUE TITLE
[admin-api] Axios throws maxBodyLength limit error for large theme uploads

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost-SDK#195]
When uploading a large theme zip, the admin-api package will throw an error `Error: Request body larger than maxBodyLength limit`.

Reviewing some related issues (https://github.com/axios/axios/pull/1985, https://github.com/yakovkhalinsky/backblaze-b2/issues/45), it would appear that although `axios` has a default `maxContentLimit` of `-1` which should be "limitless" that does not work for PUT/POST requests which pick up a default limit of 10MB from the underlying `follow-request` dependency.

From the responses in https://github.com/yakovkhalinsky/backblaze-b2/issues/45 it sounds like we could try setting the axios default `maxContentLength` to `Infinity`.

**Comment by pascalandy** [comment]
Thanks for caring about this issue :)
