### ISSUE TITLE
Create members layer0 sdk

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost-SDK#20]
This is the lowest layer of the sdk - it will interact with the iframe directly

requirements:

- Validates all messages are coming from iframe
- Can get session existence from iframe
- Can request iframe for token (with params)
- Can delete session existence from iframe
- Can get service config from iframe (e.g. login url)
- Can listen to any “event” from iframe e.g.
```js
function listen(iframe, fn) {
  iframe.addEventListener('message', function (event) {
    if (event.data.type === 'event') fn(event.data);
  });
}
```

**Comment by peterzimon** [comment]
Moving issue to a note
