### ISSUE TITLE
Update Content API's Axios version to 19.2

### ISSUE THREAD

**Issue by MatheusMK3** [TryGhost/Ghost-SDK#208]
### Issue Summary

In Axios 19.2 they fixed a bug where if the URL had the word `javascript` anywhere on it, then it would be deemed as a XSS attempt and the request would fail. I found this because my blog's front-end is a Vue application that fetches content using the Content API and was getting a weird "post not found" error whenever I tried to access a post of mine which the slug contains `javascript` on it.

### To Reproduce

1. Try to fetch a post that has `javascript` on the slug
2. The request won't happen and you will get an error back

**Comment by MatheusMK3** [comment]
@daniellockyer if possible, take a look at this please.

**Comment by daniellockyer** [comment]
Hey @MatheusMK3, I just fixed this in https://github.com/TryGhost/Ghost-SDK/pull/206. Will be released soon :smile:
