### ISSUE TITLE
Strange Content API return type

### ISSUE THREAD

**Issue by Gwenael22** [TryGhost/Ghost-SDK#213]
### Issue Summary
Hello,

When i request a list of posts, the client API return an array of posts objects with a meta object at the root of this array. As i use Typescript with "@types/tryghost__content-api", this array is not strongly typed and i can not work with this type of array.

Example : 
```javascript
[ 
{
    id: '5e4a9fa6b5eeed1d57bc400f',
    uuid: 'acaaa168-bf1a-4193-9ae9-90ff1b452d2a',
    title: 'my first article'
},
{
   id: '5e46c4b0bb3f2813da132685',
    uuid: '3e208441-8f24-43bc-bc02-20f0d3db9e1e',
    title: 'my second article',
},
meta: {
    pagination: { page: 1, limit: 4, pages: 1, total: 2, next: null, prev: null }
  }
]
```
As coded in "@types/tryghost__content-api", i was waiting an object like : 
```javascript
posts: 
[ 
{
    id: '5e4a9fa6b5eeed1d57bc400f',
    uuid: 'acaaa168-bf1a-4193-9ae9-90ff1b452d2a',
    title: 'my first article'
},
{
   id: '5e46c4b0bb3f2813da132685',
    uuid: '3e208441-8f24-43bc-bc02-20f0d3db9e1e',
    title: 'my second article',
},
],
meta: {
    pagination: { page: 1, limit: 4, pages: 1, total: 2, next: null, prev: null }
  }
```

### To Reproduce

1. Call the posts API with a Tag filter
`BlogApi.posts
    .browse({
      limit: 4,
      include: ['tags', 'authors'],
      filter: 'tag:' + category,
    })
    .catch(err => {
      console.error(err);
      throw err;
    });`

2. Use the result API

### Technical details:

* Ghost Version: 3.9.0
* Next.js Version : 9.0.5
* Axios Version : 0.19.2
* Node Version: 12.16.1
* OS: Ubuntu

**Comment by kevinansfield** [comment]
@Gwenael22 this sounds like a bug in `@types/tryghost__content-api` which isn't something made by us.

Right now, the response from the SDK is as expected, it's an extended array with a `meta` property.

**Comment by allouis** [comment]
You can raise a PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/tryghost__content-api/index.d.ts

here's an example of how to type it correctly https://www.typescriptlang.org/play/#code/C4TwDgpgBAshwEMoF4oG8CwAoKupgCcB7MALigGdgCBLAOwHNsBfbUSKAcQAsiqAZGlQA8AFQB8KKAEECBBCDGSAZOigBbeAnJxEUVljbhoABT7ApmHHhoATclVqMW2bABt4UYN3oNyPc0ERMypJVABtNCg7cgByAEZY-QBdIA

**Comment by Gwenael22** [comment]
I do not consider that it is a clean code but it seems that it is not problematic for you ...

**Comment by microvn** [comment]
This issue is similar to the original (@tryghost/content-api)
It is really not clear with return data
