### ISSUE TITLE
Content api does not return meta field, only post array

### ISSUE THREAD

**Issue by tvld** [TryGhost/Ghost-SDK#214]
I run this code: 
```js
const api = new GhostContentAPI({
  url: CONFIG.GHOST.URL,
  key: CONFIG.GHOST.API_KEY.CONTENT,
  version: 'v3'
})

export async function getPost (postSlug, { include='tags,authors' } ) {
  const post = await api.posts
    .read({
      slug: postSlug,
      include: include,
    })
    .catch((err) => {
      logError(`getPost(${postSlug})`, err)
      return { statusCode: 404, message: 'getPost() failed' }
    })
  return post
}
```
But the api only returns an array with posts, there is not meta object appended.

I see the json response itself from the server does include the meta field. Is it a bug that it is lost in the sdk ?

**Comment by kevinansfield** [comment]
This is as expected.

`api.posts.read` does not contain any pagination data because it's a single-record query.
`api.posts.browse` will contain pagination data in the meta property because it's a multi-record query.

**Comment by tvld** [comment]
ok, thanks... but with ``posts.browse`` we do not need the previous / next slug as we already have them in the response array anyway, unless off limit. So I need to make multiple calls to allow for stepping through posts...
