### ISSUE TITLE
@tryghost/content-api in a vue stack : core-js These dependencies were not found: 260 261

### ISSUE THREAD

**Issue by PierreBrisorgueil** [TryGhost/Ghost-SDK#343]
### Issue Summary

https://travis-ci.org/github/weareopensource/Vue/builds/717478799

```
 core-js/modules/es6.array.iterator in ./node_modules/@tryghost/content-api/es/content-api.js
262* core-js/modules/es6.function.name in ./node_modules/@tryghost/content-api/es/content-api.js
263* core-js/modules/es6.object.assign in ./node_modules/@tryghost/content-api/es/content-api.js
264* core-js/modules/es6.object.keys in ./node_modules/@tryghost/content-api/es/content-api.js
265* core-js/modules/es6.object.to-string in ./node_modules/@tryghost/content-api/es/content-api.js
266* core-js/modules/es6.promise in ./node_modules/@tryghost/content-api/es/content-api.js
267* core-js/modules/es6.string.ends-with in ./node_modules/@tryghost/content-api/es/content-api.js
268* core-js/modules/es6.string.starts-with in ./node_modules/@tryghost/content-api/es/content-api.js
269* core-js/modules/es7.array.includes in ./node_modules/@tryghost/content-api/es/content-api.js
270* core-js/modules/web.dom.iterable in ./node_modules/@tryghost/content-api/es/content-api.js
```

probably linked to Babel and core-js:  https://github.com/gatsbyjs/gatsby/issues/7862

I tried to clear the cache relaunched several times, checked that it was not linked to another dependency upgrade ... 
without success, I trace the bug, if that can help

### To Reproduce

Really no idea, just add content-API as a dependency of a Vue project, npm run build will fail. 

### Technical details:

* Ghost Version: latest
* Node Version: 10 12 13
* Database: SQLite

### Tempo solution :

downgrade to 1.4.2 :     "@tryghost/content-api": "1.4.2"

https://travis-ci.org/github/weareopensource/Vue/builds/717319344

**Comment by daniellockyer** [comment]
Hey @PierreBrisorgueil :wave: I just pushed `content-api` 1.4.4, which _might_ contain the [fix](https://github.com/TryGhost/Ghost-SDK/commit/e3c9dc3c4e669e2cec5b7b833e51c127060f8f0f) to resolve this. Would you be able to update and check?

**Comment by PierreBrisorgueil** [comment]
Hello @daniellockyer, everything is ok ! thx a lot ! 

https://github.com/weareopensource/Vue/pull/659
