### ISSUE TITLE
Adding a new post issue

### ISSUE THREAD

**Issue by LinkOut** [TryGhost/Ghost-SDK#350]
Hi, im trying to use the ghost API to add a post on the website…

```
const GHOST_API = new GhostAdminAPI({
    url: END_POINT,
    version: "v3",
    key: GHOST_KEY
});

GHOST_API.posts.add({
    title: 'My first draft API post',
    mobiledoc: '{\"version\":\"0.3.1\",\"atoms\":[],\"cards\":[],\"markups\":[],\"sections\":[[1,\"p\",[[0,[],0,\"My post content. Work in progress...\"]]]]}'
}).then(result => {
    res.send(JSON.stringify(result) + " - SUCCESS!")
}).catch(err => {
    res.send(JSON.stringify(err) + " -  ERROR!")
});
```

The `result `being the Array of posts i already have, but it does not add the new one.

Ive used this guide: https://ghost.org/docs/api/v3/javascript/admin/

Thanks for suggestions

**Comment by kevinansfield** [comment]
Hey @aidenmitchell :wave: We ask that you please do not use GitHub for help or support 😄. We use GitHub solely for bug-tracking and on-going feature development.

Many questions can be answered by reviewing our [documentation](https://ghost.org/docs/). If you can't find an answer then our [forum](https://forum.ghost.org) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

**Comment by aidenmitchell** [comment]
@kevinansfield Why was I tagged here?

**Comment by kevinansfield** [comment]
@aidenmitchell apologies, I copy/pasted a saved reply from the Ghost repo because the tag automation wasn't set up in this repo and I completely missed that I'd grabbed your handle when copying

**Comment by aidenmitchell** [comment]
No worries! Just wondering, thanks.
