### ISSUE TITLE
Reconsider client builds of `admin-api` package

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost-SDK#47]
The `@tryghost/admin-api` library should not be used in a client-side app as there is no way to protect the Admin API Key. Using it in a client-side app means any user of that app gets full write access to the Admin API.

Should we discourage that practice by removing the explicitly-client-side UMD bundle?

**Comment by ErisDS** [comment]
100% we need to not have client builds for the admin API 👍

**Comment by kirrg001** [comment]
Makes 100% sense to me too!

**Comment by kirrg001** [comment]
Re-using this issue to remove rollup completely.
