### ISSUE TITLE
build fails in webpack/creact react app because webpack can't find the precompiled code

### ISSUE THREAD

**Issue by r3wt** [TryGhost/Ghost-SDK#49]
create react app disallows compiling code from outside the source directory, so it relies on modules to provide their code transpiled to es5 or whatever. for some reason this isn't working with your package for `@tryghost/content-api`. i am looking for a work around to get my build working again. i don't know much about this, if you can offer any insight i would appreciate it. 

for now i am working around it by copying `lib/index.js` directly to my project src, so it can be compiled.

**Comment by ErisDS** [comment]
@r3wt can you provide exact reproduction steps please?

**Comment by r3wt** [comment]
@ErisDS I take it you don't have experience with create-react-app?

basically to reproduce just:

1. create a project with create react app
2. install this package
3. add an import of the module into the src for the new app
4. try to build the app with `npm run build`. it will fail because webpack can't find the umd build for some reason.

**Comment by kevinansfield** [comment]
Hi @r3wt 👋 Can you try upgrading to the new 1.2.0 version to see if that works? I tracked down the issue and left a more extensive writeup here if you're interested https://github.com/TryGhost/Ghost-SDK/issues/67#issuecomment-473019287
