### ISSUE TITLE
jsdom does not support Node v6

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-SDK#51]
See: https://github.com/jsdom/jsdom/commit/0cba358253fd5530af0685ac48c2535992464d06

Is it possible to pin jsdom to 12.0.0?

**Comment by ErisDS** [comment]
12.0.0 doesn't support Node v6 as far as I can tell?

**Comment by kirrg001** [comment]
They removed the package.json engine limitation after 12.0.0.

If 12.0.0 does not work, then the question is: can we ping jsdom to 11.12.0?

**Comment by gargol** [comment]
> Versions of jsdom below v12 still work with Node.js v6, but are unsupported

Will check the performance difference of current (`13.2.0`) with `11.12.0` and if it's similar to what is now, think there's no problem pinning that version.

**Comment by gargol** [comment]
@kirrg001 Recapping a convo that happened offline. We decided to make HTML format support optional for node versions ^8, so we don't have to worry about the support of v6 which will be dropped in less than 2 months anyway.
