### ISSUE TITLE
Add missing endpoints to Admin SDK

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-SDK#58]
We have added:

- posts
- webhooks
- subscribers
- images

**These are still missing:**

- tags
- pages
- users
- themes
- config
- site

Reference: https://github.com/TryGhost/Ghost/blob/master/core/server/web/api/v2/admin/middleware.js

**Comment by june07** [comment]
Any plans to add the /users endpoint?  Was this issue being closed the answer?
