### ISSUE TITLE
Add Travis

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-SDK#62]
🌝

**Comment by ErisDS** [comment]
Updating slimer to do this.

**Comment by ErisDS** [comment]
merp wasn't that easy

**Comment by kirrg001** [comment]
Closed via https://github.com/TryGhost/Ghost-SDK/commit/806718c57e7c1f4475f7dad6fe3b27de4d552c88 and https://github.com/TryGhost/Ghost-SDK/commit/0d248e1eb2f69bba8dc2f0c3fd67013648590604 👍
