### ISSUE TITLE
Travis does not run on Node v6 at all

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-SDK#66]
`@tryghost/html-to-mobiledoc` has a dependency to `jsdom` (13.2.0).

`jsdom` dropped support for Node v6.

The problem is that no tests are executed for Node v6, because the installation fails. Is that fixable? Have not looked into it.

**Comment by kevinansfield** [comment]
There's no hard dependency on the latest version of `jsdom`, we could pin the last version with node 6 support until the 6 LTS is dropped?

**Comment by kevinansfield** [comment]
Does this also impact Ghost seeing as we use it for `html` input parsing?

**Comment by kirrg001** [comment]
> Does this also impact Ghost seeing as we use it for html input parsing?

Ghost has `@tryghost/html-to-mobiledoc` as optional dependency :)

**Comment by ErisDS** [comment]
Given that node v6 support ends in ~6weeks, we should find the quickest and simplest solution, i.e exclude the v6 tests. I have no expectation that html-to-mobiledoc ever works on node 6.

**Comment by ErisDS** [comment]
closed by 6eed3eb4ef0b93e1be0ac750fe984dd0bda8847e
