### ISSUE TITLE
Create Members SDK Layer 2

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost-SDK#9]
This should be a simple drop in script - it will rely on the Layer 1 SDK
```html
<button data-members-signin>Beam me up scotty</button>
<button data-members-signout>Get me outta here</button>
<script src="/members-sdk-layer-2.js"></script>
```

This will hide the buttons depending on if you're logged in, and initiate signin/signout flows when they are clicked

**Comment by JohnONolan** [comment]
Ideally the integration would be a little more minimal like Netlify Identity? Eg. https://css-tricks.com/forms-auth-and-serverless-functions-on-gatsby-and-netlify/

```
<div data-netlify-identity-menu></div>
```

👆🏼 Empty div which the script manipulates. (If loading fails, then nothing appears, which is a good safety net)

IRL context: https://github.com/JohnONolan/Rediverge/blob/master/src/components/header.js#L20

Logic: https://github.com/JohnONolan/Rediverge/blob/master/src/pages/beta.js#L22:L37

**Comment by allouis** [comment]
The Rediverge repo is private i think - so I cannae see what's in them. 

I think you're right that ideally it would be more minimal - but this is "Layer 2" of the SDK - The first layer to do any UI manipulation, we're trying to build this up so that a developer can jump in at any layer and have as much customization as they like.

I 100% think we should build something that take an empty div and does _everything_ but maybe not right now? This allows us to put the CTA for signin/signout in casper, and we don't have to create the members service up front to load these from, or hardcode them into this SDK.

**Comment by JohnONolan** [comment]
Ah shit, forgot about that - it's basically just an implementation of that's in that tutorial link though.

Rest makes sense 👍👍

**Comment by allouis** [comment]
Cool :+1: thanks!
